task_homepage:
    path:     /
    defaults: { _controller: TaskBundle:Default:index }
    
create_task:
    path:     /create-task
    defaults: { _controller: TaskBundle:Default:create }
    
edit_task:
    path:     /edit-task/{id}
    defaults: { _controller: TaskBundle:Default:edit }
    
delete_task:
    path:     /delete-task/{id}
    defaults: { _controller: TaskBundle:Default:delete }