task_homepage:
    path:     /{_locale}/
    defaults: { _controller: TaskBundle:Default:index }
    
create_task:
    path:     /{_locale}/create-task
    defaults: { _controller: TaskBundle:Default:create }
    
edit_task:
    path:     /{_locale}/edit-task/{id}
    defaults: { _controller: TaskBundle:Default:edit }
    
delete_task:
    path:     /{_locale}/delete-task/{id}
    defaults: { _controller: TaskBundle:Default:delete }
   
admin:
    resource: "@TaskBundle/Controller/DefaultController.php"
    type:     annotation
    
login:
    resource: "@TaskBundle/Controller/SecurityController.php"
    type:     annotation
    
logout:
    path: /logout

register:
    path:     /{_locale}/register
    defaults: { _controller: MyUserBundle:Default:register}
    
manage_users:
    path:     /{_locale}/manage-users
    defaults: { _controller: MyUserBundle:Default:manage}

invalidate_user:
    path:     /{_locale}/invalidate-user/{id}
    defaults: { _controller: MyUserBundle:Default:invalidate}

validate_user:
    path:     /{_locale}/validate-user/{id}
    defaults: { _controller: MyUserBundle:Default:validate}

    