# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory:
#            memory:
#                users:
#                    user:
#                        password: user
#                        roles: 'ROLE_USER'
#                    admin:
#                        password: admin
#                        roles: 'ROLE_ADMIN'
        users:
            entity: {class: MyUserBundle:User, property: username}
            
    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
                        
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        My\UserBundle\Entity\User:
            algorithm:  sha1
            encode_as_base64: false
            iterations: 1
        

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/$, roles: ROLE_USER}
        #- { path: ^/(.+), roles: ROLE_ADMIN }
            