# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    my_tasks.last_tasks:
        class: My\TaskBundle\Model\LastTasks
        arguments: ["@doctrine.orm.entity_manager"]
        
    my_tasks.tasks_listener:
        class: My\TaskBundle\Event\TasksListener
        arguments: ["@monolog.logger"]
        tags:
            - {name: kernel.event_listener, event: task.create, method: onTaskCreate}
            - {name: kernel.event_listener, event: task.edit, method: onTaskEdit}
            - {name: kernel.event_listener, event: task.delete, method: onTaskDelete}
