My\TaskBundle\Entity\Task:
    type: entity
    table: null
    repositoryClass: My\TaskBundle\Repository\TaskRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        createdAt:
            type: datetime
    lifecycleCallbacks: {  }
